## Experiment No 10
## Create Dataset and Load Dataset
## Name:Atharva Jadhav
## PRN:25070123027
### Batch:ENTC A2

In [ ]:
import pandas as pd
data_1={"Roll No":[1,2,3,4,5],
        "Gender":["Male","Female","Female","Male","Female"],
        "Department":["CS","ENTC","Civil","Mechanical","AI"],
        "CGPA":[8,9,7,8,9],
        "Year":["1st","1st","2nd","4th","3rd"]
}
df=pd.DataFrame(data_1)
df.to_csv("data_1.csv",index=False)
df

   Roll No  Gender  Department  CGPA Year
0        1    Male          CS     8  1st
1        2  Female        ENTC     9  1st
2        3  Female       Civil     7  2nd
3        4    Male  Mechanical     8  4th
4        5  Female          AI     9  3rd

In [ ]:
# To find the shape of df
df.shape

(5, 5)

In [ ]:
# To find the size of df
df.size

25

In [ ]:
# To find the info of df
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Roll No     5 non-null      int64
 1   Gender      5 non-null      object
 2   Department  5 non-null      object
 3   CGPA        5 non-null      int64
 4   Year        5 non-null      object
dtypes: int64(2), object(3)
memory usage: 332.0+ bytes

In [ ]:
# To find the describe the df
df.describe()

        Roll No     CGPA
count  5.000000  5.00000
mean   3.000000  8.20000
std    1.581139  0.83666
min    1.000000  7.00000
25%    2.000000  8.00000
50%    3.000000  8.00000
75%    4.000000  9.00000
max    5.000000  9.00000

In [ ]:
# Access information  of column department
df["Department"]

0            CS
1          ENTC
2         Civil
3    Mechanical
4            AI
Name: Department, dtype: object

In [ ]:
# Access information of PRN 3
(df.loc[2])

Roll No            3
Gender        Female
Department     Civil
CGPA               7
Year             2nd
Name: 2, dtype: object

In [ ]:
# Find out data type of each column
df.dtypes

Roll No        int64
Gender        object
Department    object
CGPA           int64
Year          object
dtype: object

In [27]:
# Perform mean,median,mode operation
mean1=df["CGPA"].mean()
median1=df["CGPA"].median()
mode1=df["CGPA"].mode()
print(mean1)
print(median1)
print(mode1)

8.2
8.0
0    8
1    9
Name: CGPA, dtype: int64

In [29]:
# Add a New Column
df["Grade"]=["First Class","Distinction","Second Class","First Class","Distinction"]
df

   Roll No  Gender  Department  CGPA Year         Grade
0        1    Male          CS     8  1st   First Class
1        2  Female        ENTC     9  1st   Distinction
2        3  Female       Civil     7  2nd  Second Class
3        4    Male  Mechanical     8  4th   First Class
4        5  Female          AI     9  3rd   Distinction

In [30]:
# Delete a column
df.drop("Grade",axis=1,inplace=True)
df

   Roll No  Gender  Department  CGPA Year
0        1    Male          CS     8  1st
1        2  Female        ENTC     9  1st
2        3  Female       Civil     7  2nd
3        4    Male  Mechanical     8  4th
4        5  Female          AI     9  3rd

In [33]:
# CGPA of topper
max1=df["CGPA"].max()
print(max1)

9

In [31]:
# CGPA of PRN 5
df.loc[4,"CGPA"]

np.int64(9)

In [34]:
#Upload the Dataset
import pandas as pd
df=pd.read_csv("/content/Cars93 (1).csv")
df

,Manufacturer,Model,Type,Price,MPG.city,AirBags,Horsepower,Passengers,Rear.seat.room,Luggage.room
0,Acura,Integra,Small,15.9,25,NaN,140,5,26.5,11.0
1,Acura,Legend,Midsize,33.9,18,Driver & Passenger,200,5,30.0,15.0
2,Audi,90,Compact,29.1,20,Driver only,172,5,28.0,14.0
3,Audi,100,Midsize,37.7,19,Driver & Passenger,172,6,31.0,17.0
4,BMW,535i,Midsize,30.0,22,Driver only,208,4,27.0,13.0
...,...,...,...,...,...,...,...,...,...,...
88,Volkswagen,Eurovan,Van,19.7,17,NaN,109,7,34.0,NaN
89,Volkswagen,Passat,Compact,20.0,21,NaN,134,5,31.5,14.0
90,Volkswagen,Corrado,Sporty,23.3,18,NaN,178,4,26.0,15.0
91,Volvo,240,Compact,22.7,21,Driver only,114,5,29.5,14.0
92,Volvo,850,Midsize,26.7,20,Driver & Passenger,168,5,30.0,15.0

In [46]:
df.shape

(8807, 12)

In [36]:
df.size

930

In [37]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 93 entries, 0 to 92
Data columns (total 10 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Manufacturer    93 non-null     object
 1   Model           93 non-null     object
 2   Type            93 non-null     object
 3   Price           93 non-null     float64
 4   MPG.city        93 non-null     int64
 5   AirBags         59 non-null     object
 6   Horsepower      93 non-null     int64
 7   Passengers      93 non-null     int64
 8   Rear.seat.room  91 non-null     float64
 9   Luggage.room    82 non-null     float64
dtypes: float64(3), int64(3), object(4)
memory usage: 7.4+ KB

In [39]:
df.describe()

,Price,MPG.city,Horsepower,Passengers,Rear.seat.room,Luggage.room
count,93.000000,93.000000,93.000000,93.000000,91.000000,82.000000
mean,19.509677,22.365591,143.827957,5.086022,27.829670,13.890244
std,9.659430,5.619812,52.374410,1.038979,2.989072,2.997967
min,7.400000,15.000000,55.000000,2.000000,19.000000,6.000000
25%,12.200000,18.000000,103.000000,4.000000,26.000000,12.000000
50%,17.700000,21.000000,140.000000,5.000000,27.500000,14.000000
75%,23.300000,25.000000,170.000000,6.000000,30.000000,15.000000
max,61.900000,46.000000,300.000000,8.000000,36.000000,22.000000

In [43]:
# To use head() function which print the first 5 elements
df.head()

,Manufacturer,Model,Type,Price,MPG.city,AirBags,Horsepower,Passengers,Rear.seat.room,Luggage.room
0,Acura,Integra,Small,15.9,25,NaN,140,5,26.5,11.0
1,Acura,Legend,Midsize,33.9,18,Driver & Passenger,200,5,30.0,15.0
2,Audi,90,Compact,29.1,20,Driver only,172,5,28.0,14.0
3,Audi,100,Midsize,37.7,19,Driver & Passenger,172,6,31.0,17.0
4,BMW,535i,Midsize,30.0,22,Driver only,208,4,27.0,13.0

In [42]:
# To use tail() function which print the last 5 elements
df.tail()

,Manufacturer,Model,Type,Price,MPG.city,AirBags,Horsepower,Passengers,Rear.seat.room,Luggage.room
88,Volkswagen,Eurovan,Van,19.7,17,NaN,109,7,34.0,NaN
89,Volkswagen,Passat,Compact,20.0,21,NaN,134,5,31.5,14.0
90,Volkswagen,Corrado,Sporty,23.3,18,NaN,178,4,26.0,15.0
91,Volvo,240,Compact,22.7,21,Driver only,114,5,29.5,14.0
92,Volvo,850,Midsize,26.7,20,Driver & Passenger,168,5,30.0,15.0

In [44]:
#Upload the Dataset
import pandas as pd
df=pd.read_csv("/content/netflix_titles.csv")
df

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,25-Sep-21,2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
1,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,24-Sep-21,2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,24-Sep-21,2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...
3,s4,TV Show,Jailbirds New Orleans,NaN,NaN,NaN,24-Sep-21,2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo..."
4,s5,TV Show,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,24-Sep-21,2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...
...,...,...,...,...,...,...,...,...,...,...,...,...
8802,s8803,Movie,Zodiac,David Fincher,"Mark Ruffalo, Jake Gyllenhaal, Robert Downey J...",United States,20-Nov-19,2007,R,158 min,"Cult Movies, Dramas, Thrillers","A political cartoonist, a crime reporter and a..."
8803,s8804,TV Show,Zombie Dumb,NaN,NaN,NaN,01-Jul-19,2018,TV-Y7,2 Seasons,"Kids' TV, Korean TV Shows, TV Comedies","While living alone in a spooky town, a young g..."
8804,s8805,Movie,Zombieland,Ruben Fleischer,"Jesse Eisenberg, Woody Harrelson, Emma Stone, ...",United States,01-Nov-19,2009,R,88 min,"Comedies, Horror Movies",Looking to survive in a world taken over by zo...
8805,s8806,Movie,Zoom,Peter Hewitt,"Tim Allen, Courteney Cox, Chevy Chase, Kate Ma...",United States,11-Jan-20,2006,PG,88 min,"Children & Family Movies, Comedies","Dragged from civilian life, a former superhero..."
8806,s8807,Movie,Zubaan,Mozez Singh,"Vicky Kaushal, Sarah-Jane Dias, Raaghav Chanan...",India,02-Mar-19,2015,TV-14,111 min,"Dramas, International Movies, Music & Musicals",A scrappy but poor boy worms his way into a ty...

In [47]:
df.shape

(8807, 12)

In [45]:
df.size

105684

In [48]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8807 entries, 0 to 8806
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   show_id       8807 non-null   object
 1   type          8807 non-null   object
 2   title         8807 non-null   object
 3   director      6173 non-null   object
 4   cast          7982 non-null   object
 5   country       7976 non-null   object
 6   date_added    8797 non-null   object
 7   release_year  8807 non-null   int64
 8   rating        8803 non-null   object
 9   duration      8804 non-null   object
 10  listed_in     8807 non-null   object
 11  description   8807 non-null   object
dtypes: int64(1), object(11)
memory usage: 825.8+ KB

In [49]:
df.describe()

       release_year
count   8807.000000
mean    2014.180198
std        8.819312
min     1925.000000
25%     2013.000000
50%     2017.000000
75%     2019.000000
max     2021.000000

In [50]:
df.head()

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,25-Sep-21,2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
1,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,24-Sep-21,2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,24-Sep-21,2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...
3,s4,TV Show,Jailbirds New Orleans,NaN,NaN,NaN,24-Sep-21,2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo..."
4,s5,TV Show,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,24-Sep-21,2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...

In [52]:
df.tail()

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
8802,s8803,Movie,Zodiac,David Fincher,"Mark Ruffalo, Jake Gyllenhaal, Robert Downey J...",United States,20-Nov-19,2007,R,158 min,"Cult Movies, Dramas, Thrillers","A political cartoonist, a crime reporter and a..."
8803,s8804,TV Show,Zombie Dumb,NaN,NaN,NaN,01-Jul-19,2018,TV-Y7,2 Seasons,"Kids' TV, Korean TV Shows, TV Comedies","While living alone in a spooky town, a young g..."
8804,s8805,Movie,Zombieland,Ruben Fleischer,"Jesse Eisenberg, Woody Harrelson, Emma Stone, ...",United States,01-Nov-19,2009,R,88 min,"Comedies, Horror Movies",Looking to survive in a world taken over by zo...
8805,s8806,Movie,Zoom,Peter Hewitt,"Tim Allen, Courteney Cox, Chevy Chase, Kate Ma...",United States,11-Jan-20,2006,PG,88 min,"Children & Family Movies, Comedies","Dragged from civilian life, a former superhero..."
8806,s8807,Movie,Zubaan,Mozez Singh,"Vicky Kaushal, Sarah-Jane Dias, Raaghav Chanan...",India,02-Mar-19,2015,TV-14,111 min,"Dramas, International Movies, Music & Musicals",A scrappy but poor boy worms his way into a ty...